name: Deployment

on:
  workflow_dispatch
  # pull_request:
  #   branches: [ "main" ]

jobs:
  job_id:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v3

    - id: auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v0'
      with:
        name: 'cyderes-skills-api'
        runtime: 'nodejs16'
        entry_point: 'cyderes_api'
        region: 'us-west1'
        env_vars: 'WHOISAPIKEY=${{ secrets.WHOISAPIKEY }}'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        description: 'Cyderes skills challenge API'


    # Example of using the output
    - id: 'test'
      run: 'curl "${{ steps.deploy.outputs.url }}"'
